spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ${DB_URL:jdbc:mariadb://localhost:3306/orders?serverTimezone=UTC&characterEncoding=UTF-8}
        username: ${DB_USER:tester}
        password: ${DB_PASS:tester1234}
    jpa:
        hibernate:
          ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    flyway:
        baseline-on-migrate: true
        enabled: true

logging:
    level:
        org.hibernate:
            type.descriptor.sql: trace
            SQL: DEBUG
