spring:
    application:
        name: orders
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ${DB_URL:jdbc:mariadb://localhost:3306/orders?serverTimezone=UTC&characterEncoding=UTF-8}
        username: ${DB_USER:tester}
        password: ${DB_PASS:tester1234}
    jpa:
        hibernate:
          ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    flyway:
        baseline-on-migrate: true
        enabled: true
    kafka:
        consumer:
            bootstrap-servers: ${KAFKA_CONSUMER_URL:localhost:9092}
            group-id: order
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: ${KAFKA_PRODUCER_URL:localhost:9092}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
    port: 8081

logging:
    level:
        org.hibernate:
            type.descriptor.sql: trace
            SQL: DEBUG

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:9999/eureka/}
        register-with-eureka: true
        fetch-registry: true

feign:
  client:
      config:
          default:
              connectTimeout: 5000
              readTimeout: 5000


