server:
    port: 9980

spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
            - id: orders
              uri: lb://ORDERS
              predicates:
              - Path=/orders/**
            - id: payments
              uri: lb://PAYMENTS
              predicates:
              - Path=/payments/**
            - id: members
              uri: lb://MEMBERS
              predicates:
                  - Path=/members/**

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:9999/eureka/}
        register-with-eureka: true
        fetch-registry: true
